import { useState } from "react";
import { Activity, ArrowDownToLine, ArrowUpRight, Bell, Blocks, Check, ChevronRight, CircleHelp, Code2, FileText, Fingerprint, Gauge, LayoutDashboard, LockKeyhole, Plus, Search, Settings2, Shield, ShieldCheck, SlidersHorizontal, Sparkles, Terminal, Users, Wallet, Zap } from "lucide-react";
import { Area, AreaChart, CartesianGrid, XAxis, Pie, PieChart, Cell } from "recharts";
import { Button } from "@/shared/ui/kit/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/shared/ui/kit/card";
import { Badge } from "@/shared/ui/kit/badge";
import { Input } from "@/shared/ui/kit/input";
import { Progress } from "@/shared/ui/kit/progress";
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/shared/ui/kit/table";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/shared/ui/kit/tabs";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/shared/ui/kit/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/shared/ui/kit/dialog";
import { Switch } from "@/shared/ui/kit/switch";
import { Avatar, AvatarFallback } from "@/shared/ui/kit/avatar";
import { Separator } from "@/shared/ui/kit/separator";
import { ChartContainer, ChartTooltip, ChartTooltipContent } from "@/shared/ui/kit/chart";

const navigation = [{ label: "Overview", icon: LayoutDashboard }, { label: "Policies", icon: ShieldCheck }, { label: "Agents & access", icon: Users }, { label: "Models", icon: Blocks }, { label: "Budgets", icon: Wallet }, { label: "Audit log", icon: FileText }, { label: "Integrations", icon: Code2 }];
const initialPolicies = [{ name: "Prompt injection", description: "Block malicious instructions", rules: 12, enabled: true }, { name: "Sensitive data", description: "Redact personal information", rules: 8, enabled: true }, { name: "Access control", description: "Enforce agent permissions", rules: 6, enabled: true }, { name: "Model allowlist", description: "Restrict unapproved models", rules: 4, enabled: true }];
const events = [
  { time: "14:32:08", agent: "customer-support", model: "GPT-4o", action: "Completion", result: "Allowed", reason: "Passed all checks" },
  { time: "14:31:56", agent: "research-agent", model: "Claude 3.5", action: "Tool call", result: "Blocked", reason: "Prompt injection detected" },
  { time: "14:31:42", agent: "finance-assistant", model: "GPT-4o", action: "Completion", result: "Redacted", reason: "Personal information removed" },
  { time: "14:30:19", agent: "customer-support", model: "Llama 3.1", action: "Tool call", result: "Allowed", reason: "Passed all checks" },
  { time: "14:29:51", agent: "research-agent", model: "Claude 3.5", action: "Completion", result: "Blocked", reason: "Resource access denied" },
  { time: "14:29:12", agent: "finance-assistant", model: "GPT-4o", action: "Completion", result: "Allowed", reason: "Passed all checks" },
];
const traffic = Array.from({ length: 25 }, (_, i) => ({ time: `${String(i).padStart(2, "0")}:00`, allowed: [140, 125, 160, 145, 180, 165, 220, 200, 240, 215, 280, 250, 310, 270, 320, 295, 345, 310, 360, 330, 400, 375, 420, 390, 445][i], blocked: [20, 18, 25, 21, 32, 28, 40, 32, 39, 35, 48, 42, 58, 45, 62, 51, 67, 58, 72, 60, 79, 65, 81, 76, 90][i] }));
const threats = [{ name: "Prompt injection", value: 42, color: "#18181b" }, { name: "Sensitive data", value: 28, color: "#71717a" }, { name: "Unauthorized access", value: 18, color: "#a1a1aa" }, { name: "Other", value: 12, color: "#e4e4e7" }];
function SecurityPage() {
  const [section, setSection] = useState("Overview");
  const [period, setPeriod] = useState("24h");
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("All events");
  const [policies, setPolicies] = useState(initialPolicies);
  const [dialog, setDialog] = useState(false);
  const [policyName, setPolicyName] = useState("");
  const [notice, setNotice] = useState("");
  const [selectedEvent, setSelectedEvent] = useState<(typeof events)[number] | null>(null);
  const visibleEvents = events.filter(event => `${event.agent} ${event.reason} ${event.model}`.toLowerCase().includes(search.toLowerCase()) && (filter === "All events" || event.result === filter));
  const multiplier = period === "7d" ? 7 : period === "30d" ? 30 : 1;
  function exportEvents() {
    const blob = new Blob([["Time,Agent,Model,Action,Result,Reason", ...visibleEvents.map(event => Object.values(event).join(","))].join("\n")], { type: "text/csv" });
    const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "sentinel-events.csv"; link.click(); URL.revokeObjectURL(url); setNotice("Event report exported.");
  }
  return <div className="min-h-screen bg-zinc-50 text-zinc-950 lg:flex">
    <aside className="flex flex-col border-r bg-white lg:fixed lg:inset-y-0 lg:w-60">
      <div className="flex h-20 items-center gap-2.5 px-6"><div className="flex size-9 items-center justify-center rounded-xl bg-zinc-950 text-white"><Shield className="size-5" /></div><span className="text-lg font-semibold tracking-tight">sentinel<span className="text-zinc-400">.</span></span><Badge variant="outline" className="ml-auto text-[10px]">BETA</Badge></div>
      <div className="px-4"><Button variant="outline" className="h-11 w-full justify-start gap-3"><Avatar className="size-6"><AvatarFallback className="bg-zinc-100 text-xs">A</AvatarFallback></Avatar>Acme workspace<ChevronRight className="ml-auto size-4 text-zinc-400" /></Button></div>
      <div className="px-6 pb-2 pt-7 text-[10px] font-medium tracking-widest text-zinc-400">WORKSPACE</div>
      <nav className="flex gap-1 overflow-x-auto px-3 lg:flex-col">{navigation.map(({ label, icon: Icon }) => <Button key={label} variant={section === label ? "secondary" : "ghost"} onClick={() => { setSection(label); setNotice(""); }} className={`h-10 justify-start gap-3 px-3 ${section === label ? "font-semibold" : "text-zinc-500"}`}><Icon className="size-4" />{label}{label === "Policies" && <span className="ml-auto text-xs text-zinc-400">{policies.length}</span>}</Button>)}</nav>
      <div className="mt-auto hidden px-4 pb-4 pt-16 lg:block"><Card className="gap-3 bg-zinc-50 py-4 shadow-none"><CardContent className="space-y-3 px-4"><div className="flex items-center gap-2 text-sm font-medium"><Sparkles className="size-4" />A little more peace of mind</div><p className="text-xs leading-5 text-muted-foreground">Advanced protection for every agent in your workspace.</p><Button variant="outline" className="w-full" onClick={() => setNotice("Your workspace is on the Pro preview plan.")}>Explore Pro<ArrowUpRight /></Button></CardContent></Card><Button variant="ghost" className="mt-4 w-full justify-start text-muted-foreground" onClick={() => setNotice("Need a hand? Contact support@sentinel.example.")}><CircleHelp />Help & documentation<ArrowUpRight className="ml-auto" /></Button><Separator className="my-3" /><div className="flex items-center gap-3 px-2"><Avatar><AvatarFallback>JD</AvatarFallback></Avatar><div className="text-sm"><p className="font-medium">Jamie Davis</p><p className="text-xs text-muted-foreground">Workspace admin</p></div><Settings2 className="ml-auto size-4 text-muted-foreground" /></div></div>
    </aside>
    <div className="min-w-0 flex-1 lg:ml-60"><header className="flex h-16 items-center justify-between border-b bg-white px-5 lg:px-8"><div className="flex items-center gap-2 text-sm text-zinc-400">Workspace<ChevronRight className="size-3" /><span className="text-zinc-800">{section}</span></div><div className="flex items-center gap-4"><Badge variant="outline" className="gap-2 font-normal"><span className="size-1.5 rounded-full bg-emerald-500" />All systems operational</Badge><Button variant="ghost" size="icon" aria-label="Notifications" onClick={() => setNotice("You're all caught up. No new security alerts.")}><Bell /></Button></div></header>
    <main className="mx-auto max-w-[1500px] space-y-6 p-5 lg:p-8">
      <div className="flex flex-wrap items-center justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-xs text-muted-foreground"><ShieldCheck className="size-3.5" />YOUR AI, UNDER CONTROL</div><h1 className="text-3xl font-semibold tracking-tight">{section === "Overview" ? "Security overview" : section}</h1><p className="mt-2 text-sm text-muted-foreground">A clear view of your AI traffic, risks, and protection.</p></div><div className="flex gap-2"><Select value={period} onValueChange={setPeriod}><SelectTrigger className="w-36 bg-white"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="24h">Last 24 hours</SelectItem><SelectItem value="7d">Last 7 days</SelectItem><SelectItem value="30d">Last 30 days</SelectItem></SelectContent></Select><Button variant="outline" onClick={exportEvents}><ArrowDownToLine />Export</Button><Button onClick={() => setDialog(true)}><Plus />New policy</Button></div></div>
      {notice && <div role="status" className="flex items-center justify-between rounded-lg border bg-white px-4 py-3 text-sm"><span>{notice}</span><Button variant="ghost" size="sm" onClick={() => setNotice("")}>Dismiss</Button></div>}
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{ label: "Total requests", value: (24836 * multiplier).toLocaleString(), detail: "+18.6%", caption: "vs. previous period", icon: Activity }, { label: "Threats blocked", value: (1248 * multiplier).toLocaleString(), detail: "5.0%", caption: "of total requests", icon: Shield }, { label: "Data redacted", value: (386 * multiplier).toLocaleString(), detail: "1.6%", caption: "of total requests", icon: Fingerprint }, { label: "Budget used", value: `$${(128.4 * multiplier).toFixed(2)}`, detail: "25.7%", caption: "of $500 daily limit", icon: Wallet }].map(({ label, value, detail, caption, icon: Icon }) => <Card key={label} className="gap-3 py-5 shadow-none"><CardContent className="px-5"><div className="flex items-center justify-between text-sm text-muted-foreground">{label}<Icon className="size-4" /></div><div className="mt-3 text-[30px] font-semibold tracking-tight">{value}</div><div className="mt-2 flex items-center gap-2 text-xs"><Badge variant="secondary" className={label === "Total requests" ? "bg-emerald-50 text-emerald-700" : ""}>{label === "Total requests" && <ArrowUpRight className="size-3" />}{detail}</Badge><span className="text-muted-foreground">{caption}</span></div></CardContent></Card>)}</div>
      {section === "Overview" && <div className="grid gap-5 xl:grid-cols-3"><Card className="shadow-none xl:col-span-2"><CardHeader className="flex-row items-start justify-between"><div><CardTitle>Request activity</CardTitle><CardDescription className="mt-1.5">Traffic flowing through your security layer</CardDescription></div><Badge variant="outline" className="font-normal">{period === "24h" ? "Today" : period === "7d" ? "7 days" : "30 days"}</Badge></CardHeader><CardContent><ChartContainer config={{ allowed: { label: "Allowed", color: "#18181b" }, blocked: { label: "Blocked", color: "#a1a1aa" } }} className="h-56 w-full"><AreaChart data={traffic.map(point => ({ ...point, allowed: point.allowed * multiplier, blocked: point.blocked * multiplier }))} margin={{ left: 0, right: 5, top: 10 }}><defs><linearGradient id="traffic-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#71717a" stopOpacity={0.18} /><stop offset="100%" stopColor="#71717a" stopOpacity={0.01} /></linearGradient></defs><CartesianGrid vertical={false} strokeDasharray="3 3" /><XAxis dataKey="time" tickLine={false} axisLine={false} interval={5} tickMargin={12} /><ChartTooltip content={<ChartTooltipContent />} /><Area type="monotone" dataKey="allowed" stroke="#27272a" fill="url(#traffic-fill)" strokeWidth={2} /><Area type="monotone" dataKey="blocked" stroke="#a1a1aa" fill="transparent" strokeWidth={2} /></AreaChart></ChartContainer><div className="mt-4 flex justify-center gap-5 text-xs text-muted-foreground"><span className="flex items-center gap-2"><span className="size-2 rounded-full bg-zinc-900" />Allowed requests</span><span className="flex items-center gap-2"><span className="size-2 rounded-full bg-zinc-400" />Blocked requests</span></div></CardContent></Card><Card className="shadow-none"><CardHeader><CardTitle>Threat breakdown</CardTitle><CardDescription>What we're keeping out</CardDescription></CardHeader><CardContent><div className="relative"><ChartContainer config={Object.fromEntries(threats.map(t => [t.name, { label: t.name, color: t.color }]))} className="mx-auto h-40 w-40"><PieChart><ChartTooltip content={<ChartTooltipContent nameKey="name" />} /><Pie data={threats} dataKey="value" nameKey="name" innerRadius={53} outerRadius={72} paddingAngle={4} strokeWidth={0}>{threats.map(t => <Cell key={t.name} fill={t.color} />)}</Pie></PieChart></ChartContainer><div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center"><strong className="text-2xl tracking-tight">{(1248 * multiplier).toLocaleString()}</strong><span className="text-[11px] text-muted-foreground">threats blocked</span></div></div><div className="mt-5 space-y-3">{threats.map(t => <div key={t.name} className="flex items-center gap-2 text-xs"><span className="size-2 rounded-full" style={{ background: t.color }} /><span className="text-muted-foreground">{t.name}</span><span className="ml-auto font-medium">{t.value}%</span></div>)}</div></CardContent></Card></div>}
      <div className="grid gap-5 xl:grid-cols-3"><Card className="min-w-0 shadow-none xl:col-span-2"><CardHeader className="flex-row justify-between"><div><CardTitle>Recent events</CardTitle><CardDescription className="mt-1.5">Every request. Every decision. Full visibility.</CardDescription></div><Button variant="ghost" size="sm" onClick={() => { setSection("Audit log"); setFilter("All events"); }}>View all<ArrowUpRight /></Button></CardHeader><CardContent><div className="mb-4 flex flex-wrap gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 size-3.5 text-muted-foreground" /><Input aria-label="Search events" className="pl-9" placeholder="Search agents, models, or events…" value={search} onChange={e => setSearch(e.target.value)} /></div><Select value={filter} onValueChange={setFilter}><SelectTrigger className="w-36"><SlidersHorizontal className="size-3" /><SelectValue /></SelectTrigger><SelectContent>{["All events", "Allowed", "Blocked", "Redacted"].map(value => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></div><Table><TableHeader><TableRow><TableHead>Time</TableHead><TableHead>Agent / model</TableHead><TableHead>Action</TableHead><TableHead>Result</TableHead><TableHead className="w-8" /></TableRow></TableHeader><TableBody>{visibleEvents.map(event => <TableRow key={event.time}><TableCell className="font-mono text-xs text-muted-foreground">{event.time}</TableCell><TableCell><p className="text-xs font-medium">{event.agent}</p><p className="mt-1 text-[11px] text-muted-foreground">{event.model}</p></TableCell><TableCell className="text-xs text-muted-foreground">{event.action}</TableCell><TableCell><Badge variant="outline" className={event.result === "Allowed" ? "border-emerald-200 bg-emerald-50 text-emerald-700" : event.result === "Blocked" ? "border-rose-200 bg-rose-50 text-rose-700" : "border-amber-200 bg-amber-50 text-amber-700"}><span className="size-1 rounded-full bg-current" />{event.result}</Badge></TableCell><TableCell><Button variant="ghost" size="icon-sm" aria-label={`Inspect event at ${event.time}`} onClick={() => setSelectedEvent(event)}><ChevronRight /></Button></TableCell></TableRow>)}</TableBody></Table>{visibleEvents.length === 0 && <p className="py-10 text-center text-sm text-muted-foreground">No matching events. Try another search or filter.</p>}<p className="mt-4 text-xs text-muted-foreground">Showing {visibleEvents.length} events · Sample workspace data</p></CardContent></Card>
      <div className="space-y-5"><Card className="shadow-none"><CardHeader className="flex-row items-center justify-between"><CardTitle>Active protection</CardTitle><Badge variant="secondary" className="gap-1 bg-emerald-50 text-emerald-700"><Check className="size-3" />{policies.filter(p => p.enabled).length} active</Badge></CardHeader><CardContent className="space-y-4">{policies.map((policy, i) => <div key={policy.name} className="flex items-center gap-3"><div className="flex size-8 shrink-0 items-center justify-center rounded-lg bg-zinc-100"><LockKeyhole className="size-4 text-zinc-500" /></div><div className="flex-1"><p className="text-xs font-medium">{policy.name}</p><p className="mt-1 text-[11px] text-muted-foreground">{policy.rules} rules configured</p></div><Switch aria-label={`Enable ${policy.name}`} checked={policy.enabled} onCheckedChange={enabled => setPolicies(current => current.map((p, index) => index === i ? { ...p, enabled } : p))} /></div>)}<Separator /><Button variant="ghost" className="w-full text-xs" onClick={() => setDialog(true)}>Manage policies<ArrowUpRight /></Button></CardContent></Card><Card className="gap-4 shadow-none"><CardHeader className="flex-row items-center justify-between"><CardTitle>Model usage</CardTitle><Gauge className="size-4 text-muted-foreground" /></CardHeader><CardContent className="space-y-4">{[{ name: "GPT-4o", value: 54 }, { name: "Claude 3.5 Sonnet", value: 31 }, { name: "Llama 3.1", value: 15 }].map(model => <div key={model.name}><div className="mb-2 flex justify-between text-xs"><span>{model.name}</span><span className="text-muted-foreground">{model.value}%</span></div><Progress value={model.value} className="h-1.5" /></div>)}</CardContent></Card></div></div>
      <Card className="shadow-none"><CardHeader className="flex-row flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="rounded-lg bg-zinc-100 p-2"><Terminal className="size-5" /></div><div><CardTitle>Protection starts with a few lines</CardTitle><CardDescription className="mt-1">Connect your first agent and let Sentinel handle the rest.</CardDescription></div></div><Badge variant="outline"><Zap className="size-3" />5-minute setup</Badge></CardHeader><CardContent><Tabs defaultValue="python"><TabsList><TabsTrigger value="python">Python</TabsTrigger><TabsTrigger value="typescript">TypeScript</TabsTrigger><TabsTrigger value="configuration">Configuration</TabsTrigger></TabsList><TabsContent value="python"><pre className="overflow-x-auto rounded-lg bg-zinc-950 p-5 text-xs leading-6 text-zinc-300"><code>{'# Illustrative SDK integration\nfrom sentinel import Sentinel\n\nclient = Sentinel(api_key="YOUR_API_KEY")\nresponse = client.protect(agent="support", model="gpt-4o", prompt=user_input)'}</code></pre></TabsContent><TabsContent value="typescript"><pre className="overflow-x-auto rounded-lg bg-zinc-950 p-5 text-xs leading-6 text-zinc-300"><code>{'// Illustrative SDK integration\nimport { Sentinel } from "@sentinel/sdk";\n\nconst client = new Sentinel({ apiKey: "YOUR_API_KEY" });\nconst response = await client.protect({ agent: "support", model: "gpt-4o", prompt: userInput });'}</code></pre></TabsContent><TabsContent value="configuration"><pre className="overflow-x-auto rounded-lg bg-zinc-950 p-5 text-xs leading-6 text-zinc-300"><code>{'environment: production\nprotection:\n  prompt_injection: block\n  sensitive_data: redact\n  access_control: enforce\nbudget:\n  daily_limit_usd: 500'}</code></pre></TabsContent></Tabs></CardContent></Card>
      <footer className="flex flex-wrap justify-between gap-2 text-[11px] text-muted-foreground"><span className="flex items-center gap-1.5"><ShieldCheck className="size-3" />Protected by Sentinel</span><span>Demo workspace · Changes apply to this session</span></footer>
    </main></div>
    <Dialog open={dialog} onOpenChange={setDialog}><DialogContent><DialogHeader><DialogTitle>Create a protection policy</DialogTitle><DialogDescription>Add a policy to your demo workspace. New policies start enabled.</DialogDescription></DialogHeader><form onSubmit={event => { event.preventDefault(); if (!policyName.trim()) return; setPolicies(current => [...current, { name: policyName.trim(), description: "Custom policy", rules: 1, enabled: true }]); setPolicyName(""); setDialog(false); setNotice("Policy created and enabled."); }}><label htmlFor="policy-name" className="mb-2 block text-sm font-medium">Policy name</label><Input id="policy-name" value={policyName} onChange={e => setPolicyName(e.target.value)} placeholder="e.g. External tool access" required maxLength={60} /><DialogFooter className="mt-6"><Button type="button" variant="outline" onClick={() => setDialog(false)}>Cancel</Button><Button disabled={!policyName.trim()} type="submit"><Plus />Create policy</Button></DialogFooter></form></DialogContent></Dialog>
    <Dialog open={!!selectedEvent} onOpenChange={open => { if (!open) setSelectedEvent(null); }}><DialogContent><DialogHeader><DialogTitle>Request details</DialogTitle><DialogDescription>Security decision for this sample request.</DialogDescription></DialogHeader>{selectedEvent && <dl className="space-y-3">{Object.entries(selectedEvent).map(([key, value]) => <div className="flex justify-between gap-4 text-sm" key={key}><dt className="capitalize text-muted-foreground">{key}</dt><dd className="text-right font-medium">{value}</dd></div>)}</dl>}</DialogContent></Dialog>
  </div>;
}
export const Component = SecurityPage;
